### ISSUE TITLE
scs-python  inference 时报错，

### ISSUE THREAD

**Issue by UsersNGT** [jiaweihe1996/GMTracker#10]
你好，请问在使用rtx3090 进行inference时， scs报错，找不到_scs_gpu.py是什么原因，是scs不支持cuda11.0么？

**Comment by jiaweihe1996** [comment]
Did you install the gpu version of scs solver? As
```
# Install scs-gpu
pip uninstall scs
cd scs-python
python setup.py install --scs --gpu
```

**Comment by UsersNGT** [comment]
> Did you install the gpu version of scs solver? As
> 
> ```
> # Install scs-gpu
> pip uninstall scs
> cd scs-python
> python setup.py install --scs --gpu
> ```

是的，安装了，在v100服务器，cuda10上能运行，在3090，cuda11 就报错了，没有找到原因。。所以想请教一下

**Comment by jiaweihe1996** [comment]
I test only on CUDA10.0, and don't know what's wrong with CUDA11. Could you provide detailed error message when you install scs-gpu?
Maybe you could install a newer version of `scs-python` from https://github.com/bodono/scs-python. 
Another option is to use CPU version of SCS solver, with only a little bit slower. See https://github.com/jiaweihe1996/GMTracker/issues/4.

**Comment by UsersNGT** [comment]
![image](https://user-images.githubusercontent.com/48192521/140892642-f52ccade-da98-42f0-973c-f8ddc2501075.png)
this is error message in scs-gpu,
now  only use cpu version.....

**Comment by jiaweihe1996** [comment]
From this error message, it seems you do not install scs-gpu correctly. Does any error appear when you run `python setup.py install --scs --gpu`?

**Comment by UsersNGT** [comment]
root@09acf0732b67:/app/scs# python setup.py install --scs --gpu
Namespace(blas64=False, extraverbose=False, float32=False, gpu=True, gpu_atrans=True, int32=False, scs=True)
running install
running bdist_egg
running egg_info
writing scs.egg-info/PKG-INFO
writing dependency_links to scs.egg-info/dependency_links.txt
writing requirements to scs.egg-info/requires.txt
writing top-level names to scs.egg-info/top_level.txt
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/conda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/conda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/conda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/conda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2,AVX512F,AVX512CD,AVX512_SKX
    not found = AVX512_KNL,AVX512_KNM,AVX512_CNL
{'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/opt/conda/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/opt/conda/include']}
{'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/opt/conda/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/opt/conda/include']}
Adding scs 2.1.2 to easy-install.pth file

Installed /opt/conda/lib/python3.7/site-packages/scs-2.1.2-py3.7-linux-x86_64.egg
Processing dependencies for scs==2.1.2
Searching for scipy==1.6.3
Best match: scipy 1.6.3
Adding scipy 1.6.3 to easy-install.pth file

Using /opt/conda/lib/python3.7/site-packages
Searching for numpy==1.21.2
Best match: numpy 1.21.2
Adding numpy 1.21.2 to easy-install.pth file
Installing f2py script to /opt/conda/bin
Installing f2py3 script to /opt/conda/bin
Installing f2py3.7 script to /opt/conda/bin

Using /opt/conda/lib/python3.7/site-packages
Finished processing dependencies for scs==2.1.2
--------------------------------------------------------------------------
this is installing message,   appear seems no any error.

**Comment by jiaweihe1996** [comment]
Sorry. I cannot solve it. :( 
Maybe you could submit an issue in `scs-python` repo and ask them for help.

**Comment by UsersNGT** [comment]
ok ,but thank you
i have a question also, when i try to your Repetition training experiment, use det-npy.  yesterday found you open source training code，in code you used gt-npy , this why?

**Comment by jiaweihe1996** [comment]
Because if using detection bounding boxes, the track id is hard to assign. You need to assign gt ids to the detection boxes by iou or other metrics. Now using gt boxes to train is a common practice in MOT. Some papers use augmentation on gt boxes to mimic detection distribution. However, in our paper, we don't use any augmentations.
