### ISSUE TITLE
咨询贴

### ISSUE THREAD

**Issue by Yushuibo** [jiaweihe1996/GMTracker#16]
作者您好  ！
  本人在配置项目环境时候  scs-python文件 执行命令python setup.py install --scs --gpu 报错 能不能麻烦 给指点下 这块怎么配置安装  
  具体报错信息 我贴在下面 
(GMT) D:\ANACONDA\envs\GMT\Library\lib\scs-python>python setup.py install --scs --gpu
Namespace(blas64=False, extraverbose=False, float32=False, gpu=True, gpu_atrans=True, int32=False, scs=True)
running install
running bdist_egg
running egg_info
writing scs.egg-info\PKG-INFO
writing dependency_links to scs.egg-info\dependency_links.txt
writing requirements to scs.egg-info\requires.txt
writing top-level names to scs.egg-info\top_level.txt
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['D:/ANACONDA/envs/GMT\\Library\\lib']
    include_dirs = ['D:/ANACONDA/envs/GMT\\Library\\include']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['D:/ANACONDA/envs/GMT\\Library\\lib']
    include_dirs = ['D:/ANACONDA/envs/GMT\\Library\\include']
    language = f77
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['D:/ANACONDA/envs/GMT\\Library\\lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['D:/ANACONDA/envs/GMT\\Library\\lib']
    language = f77
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/ANACONDA/envs/GMT\\Library\\include']
{'libraries': ['mkl_rt'], 'library_dirs': ['D:/ANACONDA/envs/GMT\\Library\\lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['D:/ANACONDA/envs/GMT\\Library\\include']}
{'libraries': ['mkl_rt'], 'library_dirs': ['D:/ANACONDA/envs/GMT\\Library\\lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['D:/ANACONDA/envs/GMT\\Library\\include']}
warning: no directories found matching 'scs'
warning: no directories found matching 'scs\src'
warning: no directories found matching 'scs\test'
warning: no directories found matching 'scs\test\problems'
warning: no directories found matching 'scs\include'
warning: no directories found matching 'scs\linsys'
warning: no directories found matching 'scs\linsys\cpu'
warning: no directories found matching 'scs\linsys\cpu\direct'
warning: no directories found matching 'scs\linsys\cpu\indirect'
warning: no directories found matching 'scs\linsys\gpu'
warning: no directories found matching 'scs\linsys\gpu\indirect'
warning: no directories found matching 'scs\linsys\external'
warning: no directories found matching 'scs\linsys\external\amd'
warning: no directories found matching 'scs\linsys\external\qdldl'
cl : Command line warning D9002 : ignoring unknown option '-O3'
scspy.c
src/scspy.c(16): fatal error C1083: Cannot open include file: 'glbopts.h': No such file or directory
error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYTHON -DCTRLC=1 -DUSE_LAPACK -DSCIPY_MKL_H -DHAVE_CBLAS -DSCIPY_MKL_H -DHAVE_CBLAS -Iscs/include -Iscs/linsys -Iscs/linsys/cpu/direct/ -Iscs/linsys/external/amd -Iscs/linsys/external/dqlql -ID:\ANACONDA\envs\GMT\lib\site-packages\numpy\core\include -ID:/ANACONDA/envs/GMT\Library\include -ID:/ANACONDA/envs/GMT\Library\include -ID:\ANACONDA\envs\GMT\include -ID:\ANACONDA\envs\GMT\include -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE -IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt -IC:\Program Files (x86)\Windows Kits\8.1\include\shared -IC:\Program Files (x86)\Windows Kits\8.1\include\um -IC:\Program Files (x86)\Windows Kits\8.1\include\winrt /Tcsrc/scspy.c /Fobuild\temp.win-amd64-3.6\Release\src/scspy.obj -O3" failed with exit status 2

**Comment by jiaweihe1996** [comment]
Looks like you didn't clone [`scs`](https://github.com/cvxgrp/scs/tree/0fd7ea85e8b0d878cacf5b1dbce557b330422ff7) repo in the right way.
