### ISSUE TITLE
数据关联模块

### ISSUE THREAD

**Issue by z2z-gif** [jiaweihe1996/GMTracker#18]
大佬，请问下您尝试过将StrongSORT中的AFlink和GSI插入GMTracker中观察性能的对比么，不知道是会不会有提升，对您的研究方向比较感兴趣，希望大佬指点一下。

**Comment by jiaweihe1996** [comment]
Hi. I didn't try these modules in GMTracker. Maybe you could try it by yourself. If you have any other questions about the implementation details of GMTracker, please comment in this issue.
