### ISSUE TITLE
reid

### ISSUE THREAD

**Issue by zyiyid** [jiaweihe1996/GMTracker#21]
Where is the weight file obtained by reid training? I didn't find it in the project.

**Comment by LiangGaoUser** [comment]
Hi,  ,buddy, can you answer the question for me?
https://github.com/jiaweihe1996/GMTracker/issues/22

**Comment by jiaweihe1996** [comment]
You could download the weight from https://pan.baidu.com/s/1uRM5eEEciHU3Pv0tbfUjBg (code: 4s4z).
