### ISSUE TITLE
Problems of running gmtracker_app.py 

### ISSUE THREAD

**Issue by monster519** [jiaweihe1996/GMTracker#4]
Hello,when I tried to run python gmtracker_app.py --sequence_dir data/MOT17/test/MOT17-01 --detection_file npy/npytest_tracktor/MOT17-01-DPM.npy  --checkpoint_dir experiments/static/params/0001 --max_age 100 --reid_thr 0.6 --output_file results/test/MOT17-01-DPM.txt in Pycharm,it show errors as follows:

`torch.Size([2171, 512])
Loading model parameters from experiments/static/params/0001/params.pt
torch.Size([2171, 512])
Processing MOT17-01 frame 00001
Nothing to match at this level
Processing MOT17-01 frame 00002
Nothing to match at this level
Processing MOT17-01 frame 00003

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

I have no idea what causes the issue.Can you help me?

**Comment by jiaweihe1996** [comment]
How much memory do you have?

**Comment by monster519** [comment]
> 你有多少记忆？

32G

**Comment by monster519** [comment]
> How much memory do you have?

32G

**Comment by jiaweihe1996** [comment]
Could you use `pdb` to locate the line where reporting the error? And do you have GPUs? If not, please use CPU version of the SCS solver, i.e., use `prob.solve(solver=cp.SCS)` instead of  https://github.com/jiaweihe1996/GMTracker/blob/7f0e9c1d46871b609b0241af71b9e8d619e1bc0f/GMMOT/gmatching.py#L91
and https://github.com/jiaweihe1996/GMTracker/blob/7f0e9c1d46871b609b0241af71b9e8d619e1bc0f/GMMOT/gmatching.py#L107

**Comment by monster519** [comment]
> Could you use `pdb` to locate the line where reporting the error? And do you have GPUs? If not, please use CPU version of the SCS solver, i.e., use `prob.solve(solver=cp.SCS)` instead of
> 
> https://github.com/jiaweihe1996/GMTracker/blob/7f0e9c1d46871b609b0241af71b9e8d619e1bc0f/GMMOT/gmatching.py#L91
> 
> 
> and
> https://github.com/jiaweihe1996/GMTracker/blob/7f0e9c1d46871b609b0241af71b9e8d619e1bc0f/GMMOT/gmatching.py#L107
Thank you.My GPU is GTX 1080 .I haven't tried pdb yet and I'll try it and get back to you

**Comment by monster519** [comment]
> Could you use `pdb` to locate the line where reporting the error? And do you have GPUs? If not, please use CPU version of the SCS solver, i.e., use `prob.solve(solver=cp.SCS)` instead of
> 
> https://github.com/jiaweihe1996/GMTracker/blob/7f0e9c1d46871b609b0241af71b9e8d619e1bc0f/GMMOT/gmatching.py#L91
> 
> 
> and
> https://github.com/jiaweihe1996/GMTracker/blob/7f0e9c1d46871b609b0241af71b9e8d619e1bc0f/GMMOT/gmatching.py#L107

I tried to set pdb as follows:
        `pdb.set_trace()
        if Mp.shape[0] > Mp.shape[1]:
            pdb.set_trace()`

the issue might be in gmatching.py:91 and it shows:

`torch.Size([2171, 512])
Loading model parameters from experiments/static/params/0001/params.pt
torch.Size([2171, 512])
Processing MOT17-01 frame 00001
Nothing to match at this level
Processing MOT17-01 frame 00002
Nothing to match at this level
Processing MOT17-01 frame 00003
> /home/xxx/MOT/GMTracker/GMMOT/gmatching.py(81)forward()
-> if Mp.shape[0] > Mp.shape[1]:
(Pdb) c

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

**Comment by jiaweihe1996** [comment]
In MOT17-01-DPM frame 00003, `Mp.shape[0] > Mp.shape[1]` is false, and the program goes to https://github.com/jiaweihe1996/GMTracker/blob/7f0e9c1d46871b609b0241af71b9e8d619e1bc0f/GMMOT/gmatching.py#L95 So, you should set trace under the line 95 and run line by line to locate the error.

**Comment by monster519** [comment]
> 在 MOT17-01-DPM 帧 00003 中，`Mp.shape[0] > Mp.shape[1]`为假，程序转到
> 
> https://github.com/jiaweihe1996/GMTracker/blob/7f0e9c1d46871b609b0241af71b9e8d619e1bc0f/GMMOT/gmatching.py#L95
> 
> 因此，您应该在第 95 行下设置 trace 并逐行运行以定位错误。

The error should be in gmatching.py:107 ` prob.solve(solver=cp.SCS, gpu=True, use_indirect=True)`
How can I solve it?

**Comment by monster519** [comment]
> In MOT17-01-DPM frame 00003, `Mp.shape[0] > Mp.shape[1]` is false, and the program goes to
> 
> https://github.com/jiaweihe1996/GMTracker/blob/7f0e9c1d46871b609b0241af71b9e8d619e1bc0f/GMMOT/gmatching.py#L95
> 
> So, you should set trace under the line 95 and run line by line to locate the error.

The error should be in gmatching.py:107 `prob.solve(solver=cp.SCS, gpu=True, use_indirect=True)`
How can I solve it?

**Comment by jiaweihe1996** [comment]
Could you pass the SCS solver test?
```
cd scs-python
python test/solve_random_cone_prob.py
```
If not, please reinstall SCS.

**Comment by monster519** [comment]
> Could you pass the SCS solver test?
> 
> ```
> cd scs-python
> python test/solve_random_cone_prob.py
> ```
> 
> If not, please reinstall SCS.
> Or pip install scs, and use cpu version of SCS solver.

Thanks very much .I use cpu version of SCS solver to solve this error.
