### ISSUE TITLE
Question for trainGMMOT.py and GMMOT/dataloader.py.

### ISSUE THREAD

**Issue by Kenta-b** [jiaweihe1996/GMTracker#9]
When I tryed "python trainGMMOT.py" 309th line of GMMOT/dataloader.py. But "ValueError: zero-size array to reduction operation maximum which has no identity" was raised.

Since I am running the program using MOT17, I think the cause is that the conditional statement in line 298 of GMMOT/dataloader.py refers to 3D information that is not necessary, but how can I fix it?

**Comment by jiaweihe1996** [comment]
Sorry for forgetting to upload `gt.npy`. Maybe you use detection files, which are different from the ground truth format.
Please download it from [here](https://drive.google.com/file/d/18T-qNvR_YGuHtk4L3xQDg4bTOTIkBGwz/view?usp=sharing), and unzip them in ./npy/ folder, and run `python trainGMMOT.py`

**Comment by Kenta-b** [comment]
Thanks for your quick reply!
